version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./volumes/model:/app/model
    environment:
      FLASK_APP: inference_ui.py
      FLASK_RUN_HOST: 0.0.0.0
